"""Bake the Snake Pit walkable grid + key coords into a C header (one-time, committed).

Mirrors `rotmg_rl.sim.snakepit_map.load_jm` + `_nearest_walkable` so the C env loads the exact
same map the Python oracle uses. Run on a host with numpy + the map data:

    uv run python -m rotmg_rl.csim.gen_map_header > _pufferlib/ocean/dungeon/snakepit_map.h
"""

from __future__ import annotations

import sys

from rotmg_rl.sim.snakepit_map import _nearest_walkable, find_objects, load_jm


def main() -> None:
    m = load_jm()
    w, h = m.width, m.height
    boss = find_objects(m, "Stheno")
    portal = find_objects(m, "Portal")
    bx, by = _nearest_walkable(m.walkable, *(boss[0] if boss else (16, 73)))
    ex, ey = _nearest_walkable(m.walkable, *(portal[0] if portal else (110, 21)))
    flat = m.walkable.reshape(-1).astype("uint8")

    out = sys.stdout
    out.write("/* Generated by rotmg_rl.csim.gen_map_header. Do not edit by hand. */\n")
    out.write("#ifndef SNAKEPIT_MAP_H\n#define SNAKEPIT_MAP_H\n\n")
    out.write(f"#define MAP_W {w}\n#define MAP_H {h}\n")
    out.write(f"#define BOSS_X {bx}\n#define BOSS_Y {by}\n")
    out.write(f"#define ENTRANCE_X {ex}\n#define ENTRANCE_Y {ey}\n\n")
    out.write("static const unsigned char MAP_WALKABLE[MAP_H * MAP_W] = {\n")
    for i in range(0, flat.size, 40):
        chunk = ",".join(str(int(v)) for v in flat[i : i + 40])
        out.write(chunk + ",\n")
    out.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
