"""Bake the Snake Pit walkable grid + key coords into a C header (one-time, committed).

Mirrors `rotmg_rl.sim.snakepit_map.load_jm` + `_nearest_walkable` so the C env loads the exact
same map the Python oracle uses. Run on a host with numpy + the map data:

    uv run python -m rotmg_rl.csim.gen_map_header > _pufferlib/ocean/dungeon/snakepit_map.h
"""

from __future__ import annotations

import sys

import numpy as np

from rotmg_rl.sim.snakepit_map import _nearest_walkable, find_objects, geodesic_field, load_jm

# Unreachable tiles get this sentinel geodesic value (finite, so the C reward arithmetic never sees
# inf/NaN). The player only spawns/navigates on reachable walkable tiles, so it is never read in
# practice; it just keeps the baked table well-formed.
GEODESIC_UNREACHABLE = 1.0e9


def main() -> None:
    m = load_jm()
    w, h = m.width, m.height
    boss = find_objects(m, "Stheno")
    portal = find_objects(m, "Portal")
    bx, by = _nearest_walkable(m.walkable, *(boss[0] if boss else (16, 73)))
    ex, ey = _nearest_walkable(m.walkable, *(portal[0] if portal else (110, 21)))
    flat = m.walkable.reshape(-1).astype("uint8")
    geo = geodesic_field(m.walkable, (bx, by)).reshape(-1)
    geo = np.where(np.isfinite(geo), geo, GEODESIC_UNREACHABLE)

    out = sys.stdout
    out.write("/* Generated by rotmg_rl.csim.gen_map_header. Do not edit by hand. */\n")
    out.write("#ifndef SNAKEPIT_MAP_H\n#define SNAKEPIT_MAP_H\n\n")
    out.write(f"#define MAP_W {w}\n#define MAP_H {h}\n")
    out.write(f"#define BOSS_X {bx}\n#define BOSS_Y {by}\n")
    out.write(f"#define ENTRANCE_X {ex}\n#define ENTRANCE_Y {ey}\n")
    out.write(f"#define GEODESIC_UNREACHABLE {GEODESIC_UNREACHABLE:.1f}f\n\n")
    out.write("static const unsigned char MAP_WALKABLE[MAP_H * MAP_W] = {\n")
    for i in range(0, flat.size, 40):
        chunk = ",".join(str(int(v)) for v in flat[i : i + 40])
        out.write(chunk + ",\n")
    out.write("};\n\n")
    # MAP_GEODESIC: privileged distance-to-boss potential for the (training-only) approach reward.
    out.write("static const float MAP_GEODESIC[MAP_H * MAP_W] = {\n")
    for i in range(0, geo.size, 20):
        chunk = ",".join(f"{float(v):.3f}f" for v in geo[i : i + 20])
        out.write(chunk + ",\n")
    out.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
